# from scratch regular 50 m on Aube
# train_push_fine can skip checkpoint loading with train_from_scratch=true

# data configs
data_dir: /work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m/regular_50_dataset_base.bin

dynamic_dir: [
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_Q5_0_2-31.pkl',
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_Q10_0_2-31.pkl',
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_Q50_0_2-31.pkl',
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_Q100_0_5-34.pkl',
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_Q2_0_2-31.pkl',
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_Janv2018V3_0_39-68.pkl',
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_1983V1_0_12-41.pkl',
  '/work/m24046/m24046mrcr/Test_Aube_regular/dataset_50m_short/regular_50_dataset_T2V6_1910V2_0_2-31.pkl',
]

hydro_dir: [
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q5_V1.liq',
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q10_V1.liq',
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q50_V1.liq',
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q100_V1.liq',
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q2_V1.liq',
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q_Janvier2018_V3.liq',
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q_1983_V1.liq',
  '/work/m24046/m24046mrcr/Test_Aube_regular/liqu/T2_Q_1910_V2.liq',
]

# training configs
batch_size: 1
epochs: 1901
mp_layers: 10
lr: 0.0001
lr_decay_rate: 0.999995
num_input_features: 10
num_output_features: 3
num_edge_features: 3
use_q_feature: true
dt_seconds: 14400.0

# pushforward
sequence_length: 3
overlap: 3
pf_warmup_epochs: 50

# performance configs
use_apex: True
amp: True
jit: False
num_dataloader_workers: 1
do_concat_trick: True
num_processor_checkpoint_segments: 0
recompute_activation: False

seed: 0

# init_ckpt_path: "/work/m24046/m24046mrcr/paper/Experience10/Seed0/"
# init_epoch: 900

ckpt_path: "/work/m24046/m24046mrcr/Test_Aube_regular/checkpoints/config_transfer_Aube_regular_short/Seed0/"


# front loss
lambda_front: 0.0
eps_front: 0.05
tau_front: 0.03
exclude_bc_in_front: true
