# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

hydra:
  job:
    chdir: True
  run:
    dir: ./uts_Tet_full/

# data configs
data_dir: /work/m24046/m24046mrcr/TetQ2500inter_1min_chunk/TetQ2500inter_1min_base.bin
dynamic_dir : /work/m24046/m24046mrcr/TetQ2500inter_1min_chunk/TetQ2500inter_1min_0_0-500.pkl

# training configs
batch_size: 1
epochs: 1000
mp_layers: 12
num_training_samples: 1
num_training_time_steps: 2
lr: 0.0003
lr_decay_rate: 0.9999991
num_input_features: 9
num_output_features: 3
num_edge_features: 3

# performance configs
use_apex: True
amp: False
jit: False
num_dataloader_workers: 4
do_concat_trick: True
num_processor_checkpoint_segments: 0
recompute_activation: False

ckpt_path: "/work/m24046/m24046mrcr/checkpoints_Tet_full_overfit_30min_12_double"