hydra:
  job:
    chdir: True
  run:
    dir: ./new_dataset/

# data configs
data_dir: /work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Mesh8_base.bin

dynamic_dir : [
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_1400_Group_3_peak_1400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_2800_Group_2_peak_2800_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_2600_Group_4_peak_2600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_3200_Group_1_peak_3200_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_1400_Group_2_peak_1400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_2200_Group_2_peak_2200_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_2800_Group_4_peak_2800_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_3400_Group_4_peak_3400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_2400_Group_3_peak_2400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_2000_Group_2_peak_2000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_2800_Group_1_peak_2800_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_2000_Group_3_peak_2000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_3600_Group_3_peak_3600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_1400_Group_4_peak_1400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_1200_Group_3_peak_1200_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_3600_Group_4_peak_3600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_1600_Group_1_peak_1600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_2400_Group_2_peak_2400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_1800_Group_4_peak_1800_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_1800_Group_1_peak_1800_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_1000_Group_3_peak_1000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_3000_Group_1_peak_3000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_1000_Group_4_peak_1000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_2600_Group_2_peak_2600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_3000_Group_3_peak_3000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_3000_Group_2_peak_3000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_1000_Group_1_peak_1000_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_3200_Group_2_peak_3200_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_2200_Group_4_peak_2200_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_1800_Group_2_peak_1800_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_1600_Group_3_peak_1600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_2600_Group_3_peak_2600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_2_peak_3400_Group_2_peak_3400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_3400_Group_1_peak_3400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_3200_Group_3_peak_3200_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_3_peak_1800_Group_3_peak_1800_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_2400_Group_4_peak_2400_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_1_peak_3600_Group_1_peak_3600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_1600_Group_4_peak_1600_0_0-80_interpolated.pkl',
'/work/m24046/m24046mrcr/results_data_30min_35_70_maillagex8/Group_4_peak_3200_Group_4_peak_3200_0_0-80_interpolated.pkl',
]

# training configs
batch_size: 1
epochs: 901
mp_layers: 10
lr: 0.0005
lr_decay_rate: 0.999995
num_input_features: 9
num_output_features: 3
num_edge_features: 3


# performance configs
use_apex: True
amp: True
jit: False
num_dataloader_workers: 1
do_concat_trick: True
num_processor_checkpoint_segments: 0
recompute_activation: False

# pour activer le pushforward correct
sequence_length: 3        
overlap: 3                

# décroissance du teacher forcing (ex: 50 époques de warmup)
pf_warmup_epochs: 50

ckpt_path: "/work/m24046/m24046mrcr/testAter/Configx8ShortPushFront"

# front loss
lambda_front: 0.1     # 0.05–0.3 recommandé
eps_front: 0.05       # même seuil que votre CSI
tau_front: 0.02       # lissage (0.02–0.05)
exclude_bc_in_front: true